# Generated by Django 3.2.20 on 2023-07-10 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_proposal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proposal',
        ),
    ]
