# Generated by Django 3.2.20 on 2023-07-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20230710_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleproposal',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
